In [28]:
#Loading Manhattan EZ pass data set

import pandas as pd

#import polyline

#NOTE: \n is to create a new line in output.

#To read csv file of EZ pass data set
manhattanEZPass = pd.read_csv("NYC OpenData EZ Pass Reader (Midtown Manhattan).csv")

########### Data on original dataset ###########

print("Info on dataframe.", manhattanEZPass.info(), '\n')

print("Stats on dataframe.", manhattanEZPass.describe(), '\n')

print("Number of rows and columns: ",manhattanEZPass.shape, '\n') #rows and columns of data set

#Names of all the columns of the dataframe
print("Names of columns: ", manhattanEZPass.columns, '\n')

print("Number of missing values:", '\n', manhattanEZPass.isnull().sum(), '\n')

#median_calculation_timestamp shows the date of the received data (useful to know for merging)
print("Timestamps of data column:", manhattanEZPass["median_calculation_timestamp"], "\n")

print("EZ Pass DataFrame:")
print(manhattanEZPass.head(), '\n', '\n')





############ Cleaning Dataset.  #################

#Remove duplicate rows in the dataset
manhattanEZPass.drop_duplicates(inplace = True)

#Standardizing column names (making column names all lowercase)
manhattanEZPass.columns = manhattanEZPass.columns.str.lower()

print("Cleaned EZ Pass Dtaset: ")


manhattanEZPass.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351 entries, 0 to 350
Data columns (total 10 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   sid                           351 non-null    int64
 1   link_name                     351 non-null    object
 2   borough                       351 non-null    object
 3   polyline                      351 non-null    object
 4   link_length_ft                351 non-null    float64
 5   aggregation_period_sec        351 non-null    int64
 6   n_samples                     351 non-null    int64
 7   median_calculation_timestamp  351 non-null    object
 8   median_tt_sec                 351 non-null    float64
 9   median_speed_fps              351 non-null    float64
dtypes: float64(3), int64(3), object(4)
memory usage: 27.6+ KB
Info on dataframe. None

Stats on dataframe.                  sid  link_length_ft  aggregation_period_sec   n_samples  \
count     351.000000      351.000000              351.000000  351.000000
mean    94492.612536     3596.984758              494.871795   19.595442
std     56898.358185     3881.453269              448.396410   42.342905
min      1004.000000      239.570000                0.000000    0.000000
25%     48547.500000     1021.140000                0.000000    0.000000
50%     90089.000000     2190.400000              900.000000    3.000000
75%    144630.500000     3981.025000              900.000000   23.000000
max    204047.000000    20229.180000              900.000000  373.000000

       median_tt_sec  median_speed_fps
count     351.000000        351.000000
mean      145.284900          8.655385
std       242.799223         11.725244
min         0.000000          0.000000
25%         0.000000          0.000000
50%        51.500000          3.080000
75%       191.750000         14.500000
max      1804.500000         70.290000

Number of rows and columns:  (351, 10)

Names of columns:  Index(['sid', 'link_name', 'borough', 'polyline', 'link_length_ft',
       'aggregation_period_sec', 'n_samples', 'median_calculation_timestamp',
       'median_tt_sec', 'median_speed_fps'],
      dtype='object')

Number of missing values:
 sid                             0
link_name                       0
borough                         0
polyline                        0
link_length_ft                  0
aggregation_period_sec          0
n_samples                       0
median_calculation_timestamp    0
median_tt_sec                   0
median_speed_fps                0
dtype: int64

Timestamps of data column: 0      3/16/2026 16:15:01
1      3/16/2026 16:15:01
2      3/16/2026 16:15:01
3      3/16/2026 16:15:01
4      3/16/2026 16:15:01
              ...
346    3/16/2026 16:15:01
347    3/16/2026 16:15:01
348    3/16/2026 16:15:01
349    3/16/2026 16:15:01
350    3/16/2026 16:15:01
Name: median_calculation_timestamp, Length: 351, dtype: object

EZ Pass DataFrame:
    sid                                          link_name    borough  \
0  1004  42nd Street - Eastbound - Lexington Ave to 3rd...  Manhattan
1  1011  42nd Street - Westbound - Lexington Ave to Mad...  Manhattan
2  2001  Lexington Avenue - Southbound - 49th St to 42n...  Manhattan
3  3002  Lexington Avenue - Southbound - 57th St to 49t...  Manhattan
4  3006  57th Street - Eastbound - Lexington Ave to 3rd...  Manhattan

               polyline  link_length_ft  aggregation_period_sec  n_samples  \
0        agvwFxmobMfCeI          514.26                     900         28
1        _hvwF|lobMmGhS         1024.34                     900          9
2        ecwwFdynbMlZhS         1836.18                     900         55
3  ybxwF`bnbM??vRxMzJfG         2109.11                     900         36
4    kbxwFlbnbMfAiD`AuC          508.77                     900         24

  median_calculation_timestamp  median_tt_sec  median_speed_fps
0           3/16/2026 16:15:01           69.5              7.40
1           3/16/2026 16:15:01          723.0              1.42
2           3/16/2026 16:15:01          152.0             12.08
3           3/16/2026 16:15:01          125.0             16.87
4           3/16/2026 16:15:01           18.0             28.26


Cleaned EZ Pass Dtaset:

,sid,link_name,borough,polyline,link_length_ft,aggregation_period_sec,n_samples,median_calculation_timestamp,median_tt_sec,median_speed_fps
0,1004,42nd Street - Eastbound - Lexington Ave to 3rd...,Manhattan,agvwFxmobMfCeI,514.26,900,28,3/16/2026 16:15:01,69.5,7.40
1,1011,42nd Street - Westbound - Lexington Ave to Mad...,Manhattan,_hvwF|lobMmGhS,1024.34,900,9,3/16/2026 16:15:01,723.0,1.42
2,2001,Lexington Avenue - Southbound - 49th St to 42n...,Manhattan,ecwwFdynbMlZhS,1836.18,900,55,3/16/2026 16:15:01,152.0,12.08
3,3002,Lexington Avenue - Southbound - 57th St to 49t...,Manhattan,ybxwF`bnbM??vRxMzJfG,2109.11,900,36,3/16/2026 16:15:01,125.0,16.87
4,3006,57th Street - Eastbound - Lexington Ave to 3rd...,Manhattan,kbxwFlbnbMfAiD`AuC,508.77,900,24,3/16/2026 16:15:01,18.0,28.26

In [30]:
#Loading NYC Real-Time Traffic Speed Data

#To read csv file of nyc Traffic data set
nycTrafficData = pd.read_csv("NYC Real-Time Traffic Speed Data.csv")

########### Data on original dataset ###########

print("Info on dataframe.", nycTrafficData.info(), '\n')

print("Stats on dataframe.", nycTrafficData.describe(), '\n')

print("Number of rows and columns: ", nycTrafficData.shape, '\n') #rows and columns of data set

#Names of all the columns of the dataframe
print("Names of columns: ", nycTrafficData.columns, '\n')

print("Number of missing values:", '\n', nycTrafficData.isnull().sum(), '\n')


#median_calculation_timestamp shows the date of the received data (useful to know for merging)
print("Timestamps of data column:", nycTrafficData["median_calculation_timestamp"], "\n")


print("Traffic Dataframe:")
print(nycTrafficData.head())

############ Cleaning Dataset.  #################

#Remove duplicate rows in the dataset
nycTrafficData.drop_duplicates(inplace = True)

#Standardizing column names (making column names all lowercase)
nycTrafficData.columns = manhattanEZPass.columns.str.lower()

print("Cleaned EZ Pass Dataset: ")

nycTrafficData.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351 entries, 0 to 350
Data columns (total 10 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   sid                           351 non-null    int64
 1   link_name                     351 non-null    object
 2   borough                       351 non-null    object
 3   polyline                      351 non-null    object
 4   link_length_ft                351 non-null    float64
 5   aggregation_period_sec        351 non-null    int64
 6   n_samples                     351 non-null    int64
 7   median_calculation_timestamp  351 non-null    object
 8   median_tt_sec                 351 non-null    float64
 9   median_speed_fps              351 non-null    float64
dtypes: float64(3), int64(3), object(4)
memory usage: 27.6+ KB
Info on dataframe. None

Stats on dataframe.                  sid  link_length_ft  aggregation_period_sec   n_samples  \
count     351.000000      351.000000              351.000000  351.000000
mean    94492.612536     3596.984758              407.692308   15.660969
std     56898.358185     3881.453269              448.646316   36.516636
min      1004.000000      239.570000                0.000000    0.000000
25%     48547.500000     1021.140000                0.000000    0.000000
50%     90089.000000     2190.400000                0.000000    0.000000
75%    144630.500000     3981.025000              900.000000   15.000000
max    204047.000000    20229.180000              900.000000  315.000000

       median_tt_sec  median_speed_fps
count     351.000000        351.000000
mean      118.558405          7.964131
std       205.600699         12.563373
min         0.000000          0.000000
25%         0.000000          0.000000
50%         0.000000          0.000000
75%       167.500000         14.585000
max      1206.000000         69.690000

Number of rows and columns:  (351, 10)

Names of columns:  Index(['sid', 'link_name', 'borough', 'polyline', 'link_length_ft',
       'aggregation_period_sec', 'n_samples', 'median_calculation_timestamp',
       'median_tt_sec', 'median_speed_fps'],
      dtype='object')

Number of missing values:
 sid                             0
link_name                       0
borough                         0
polyline                        0
link_length_ft                  0
aggregation_period_sec          0
n_samples                       0
median_calculation_timestamp    0
median_tt_sec                   0
median_speed_fps                0
dtype: int64

Timestamps of data column: 0      3/15/2026 12:40:12
1      3/15/2026 12:40:12
2      3/15/2026 12:40:12
3      3/15/2026 12:40:12
4      3/15/2026 12:40:12
              ...
346    3/15/2026 12:40:12
347    3/15/2026 12:40:12
348    3/15/2026 12:40:12
349    3/15/2026 12:40:12
350    3/15/2026 12:40:12
Name: median_calculation_timestamp, Length: 351, dtype: object

Traffic Dataframe:
    sid                                          link_name    borough  \
0  2012  49th Street - Westbound - Lexington Ave to Mad...  Manhattan
1  3002  Lexington Avenue - Southbound - 57th St to 49t...  Manhattan
2  5006       3rd Avenue - Northbound - 49th St to 57th St  Manhattan
3  6003  57th Street - Westbound - 3rd Ave to Lexington...  Manhattan
4  8118   34th Street - Westbound - Madison Ave to 5th Ave  Manhattan

               polyline  link_length_ft  aggregation_period_sec  n_samples  \
0    ecwwFdynbMgC~HgC~H         1013.97                     900         14
1  ybxwF`bnbM??vRxMzJfG         2109.11                     900         20
2        a_wwFfonbMq^aV         2105.67                     900         20
3        a_xwFxwmbMeC|H          502.77                     900         39
4        {puwFdxpbMeC|H          502.84                     900         28

  median_calculation_timestamp  median_tt_sec  median_speed_fps
0           3/15/2026 12:40:12          616.5              1.64
1           3/15/2026 12:40:12          139.0             15.17
2           3/15/2026 12:40:12           73.5             28.65
3           3/15/2026 12:40:12           21.0             23.94
4           3/15/2026 12:40:12           24.5             20.52
Cleaned EZ Pass Dataset:

,sid,link_name,borough,polyline,link_length_ft,aggregation_period_sec,n_samples,median_calculation_timestamp,median_tt_sec,median_speed_fps
0,2012,49th Street - Westbound - Lexington Ave to Mad...,Manhattan,ecwwFdynbMgC~HgC~H,1013.97,900,14,3/15/2026 12:40:12,616.5,1.64
1,3002,Lexington Avenue - Southbound - 57th St to 49t...,Manhattan,ybxwF`bnbM??vRxMzJfG,2109.11,900,20,3/15/2026 12:40:12,139.0,15.17
2,5006,3rd Avenue - Northbound - 49th St to 57th St,Manhattan,a_wwFfonbMq^aV,2105.67,900,20,3/15/2026 12:40:12,73.5,28.65
3,6003,57th Street - Westbound - 3rd Ave to Lexington...,Manhattan,a_xwFxwmbMeC|H,502.77,900,39,3/15/2026 12:40:12,21.0,23.94
4,8118,34th Street - Westbound - Madison Ave to 5th Ave,Manhattan,{puwFdxpbMeC|H,502.84,900,28,3/15/2026 12:40:12,24.5,20.52